services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
        NODE_ENV: ${NODE_ENV}
    image: nodejs-rocketseat
    container_name: api-solid-nodejs
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "if [ \"$NODE_ENV\" = 'production' ];
             then npm run build && npm start;
             else npm run dev;
             fi"
    environment:
      - NODE_ENV=development
    restart: always

  postgres:
    image: "bitnami/postgresql:latest"
    container_name: postgres-api-solid-nodejs
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api-solid-nodejs
    volumes:
      - database-rocketseat:/bitnami/postgresql

volumes:
  database-rocketseat: