services:
  api:
    image: node:current-alpine
    container_name: api-solid-nodejs
    working_dir: /app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm install &&
               npx prisma generate &&
               npx tsx --watch src/server.ts"
    restart: unless-stopped

  postgres:
    image: "bitnami/postgresql:latest"
    container_name: postgres-api-solid-nodejs
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api-solid-nodejs
    volumes:
      - database-rocketseat:/bitnami/postgresql

volumes:
  database-rocketseat: